// <auto-generated />
using System;
using BlazorShop.Infrastructure.Data.ControlPlane;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorShop.Infrastructure.Data.ControlPlane.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    partial class ControlPlaneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.CommerceNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("node_key");

                    b.Property<string>("NodeSecret")
                        .HasColumnType("text")
                        .HasColumnName("node_secret");

                    b.Property<DateTimeOffset?>("NodeSecretUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("node_secret_updated_at");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("NodeKey")
                        .IsUnique()
                        .HasDatabaseName("commerce_node_active_node_key_uq")
                        .HasFilter("disabled_at is null");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("commerce_node", null, t =>
                        {
                            t.HasCheckConstraint("ck_commerce_node_status", "status in ('unknown', 'healthy', 'warning', 'down', 'disabled')");
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.CommerceNodeCredential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CreatedByAdminUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_admin_user_id");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_algorithm");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_id");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("node_id");

                    b.Property<DateTimeOffset?>("RevealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revealed_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<long?>("RevokedByAdminUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("revoked_by_admin_user_id");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminUserId");

                    b.HasIndex("KeyId")
                        .IsUnique();

                    b.HasIndex("NodeId");

                    b.HasIndex("RevokedByAdminUserId");

                    b.HasIndex("NodeId", "Status")
                        .HasDatabaseName("commerce_node_credential_active_node_idx")
                        .HasFilter("revoked_at is null");

                    b.ToTable("commerce_node_credential", null, t =>
                        {
                            t.HasCheckConstraint("ck_commerce_node_credential_status", "status in ('active', 'revoked', 'rotated')");
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.CommerceNodeEndpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("node_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("NodeId", "Kind")
                        .HasDatabaseName("commerce_node_endpoint_active_kind_idx")
                        .HasFilter("disabled_at is null");

                    b.ToTable("commerce_node_endpoint", null, t =>
                        {
                            t.HasCheckConstraint("ck_commerce_node_endpoint_kind", "kind in ('control_api', 'storefront', 'internal_api')");
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("node_id");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long?>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.HasIndex("NodeId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("control_action", null, t =>
                        {
                            t.HasCheckConstraint("ck_control_action_status", "status in ('queued', 'running', 'failed', 'succeeded', 'cancelled')");
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlActionAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("ActionId")
                        .HasColumnType("bigint")
                        .HasColumnName("action_id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("ActionId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("control_action_attempt", null, t =>
                        {
                            t.HasCheckConstraint("ck_control_action_attempt_status", "status in ('running', 'failed', 'succeeded', 'cancelled')");
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<long?>("ActorAdminUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_admin_user_id");

                    b.Property<string>("ActorEmail")
                        .HasColumnType("text")
                        .HasColumnName("actor_email");

                    b.Property<string>("ActorIdentityUserId")
                        .HasColumnType("text")
                        .HasColumnName("actor_identity_user_id");

                    b.Property<long?>("ControlActionId")
                        .HasColumnType("bigint")
                        .HasColumnName("control_action_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EntityPublicId")
                        .HasColumnType("text")
                        .HasColumnName("entity_public_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<long?>("NodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("node_id");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<long?>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("ActorAdminUserId");

                    b.HasIndex("ControlActionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NodeId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.HasIndex("Action", "CreatedAt");

                    b.HasIndex("ActorEmail", "CreatedAt");

                    b.ToTable("control_audit_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_control_audit_log_result", "result in ('success', 'failure', 'denied')");
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_user_id");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<long?>("StatusChangedByAdminUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("status_changed_by_admin_user_id");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text")
                        .HasColumnName("status_reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("control_plane_admin_user_active_email_uq")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("control_plane_admin_user_public_id_uq");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_control_plane_admin_user_status")
                        .HasFilter("deleted_at is null");

                    b.HasIndex("StatusChangedByAdminUserId")
                        .HasDatabaseName("ix_control_plane_admin_user_status_changed_by");

                    b.ToTable("control_plane_admin_user", null, t =>
                        {
                            t.HasCheckConstraint("ck_control_plane_admin_user_status", "status in ('active', 'disabled', 'invited')");
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUserPermission", b =>
                {
                    b.Property<long>("AdminUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("admin_user_id");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("CreatedByAdminUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_admin_user_id");

                    b.HasKey("AdminUserId", "PermissionId");

                    b.HasIndex("CreatedByAdminUserId")
                        .HasDatabaseName("ix_control_plane_admin_user_permission_created_by");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_control_plane_admin_user_permission_permission_id");

                    b.ToTable("control_plane_admin_user_permission", (string)null);
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUserRole", b =>
                {
                    b.Property<long>("AdminUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("admin_user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AdminUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("control_plane_admin_user_role", (string)null);
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlanePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("control_plane_permission", null, t =>
                        {
                            t.HasCheckConstraint("ck_control_plane_permission_key_lower", "key = lower(key)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Read node registry.",
                            Key = "nodes.read"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create, update, and disable nodes.",
                            Key = "nodes.write"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create, revoke, and rotate node credentials.",
                            Key = "credentials.rotate"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Read store registry metadata.",
                            Key = "stores.read"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create, update, archive, and assign stores.",
                            Key = "stores.write"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Read node health and capability snapshots.",
                            Key = "health.read"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Read control action state and attempts.",
                            Key = "actions.read"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Read audit logs.",
                            Key = "audit.read"
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "List and view Control Plane users.",
                            Key = "users.read"
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create, update, enable, and disable Control Plane users.",
                            Key = "users.write"
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Assign and remove Control Plane roles.",
                            Key = "roles.assign"
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Assign and remove direct Control Plane user permissions.",
                            Key = "permissions.manage"
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("control_plane_role", null, t =>
                        {
                            t.HasCheckConstraint("ck_control_plane_role_key_lower", "key = lower(key)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Full Control Plane access.",
                            IsSystem = true,
                            Key = "platform_owner",
                            Name = "Platform Owner",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Manage nodes, stores, credentials, and health operations.",
                            IsSystem = true,
                            Key = "node_operator",
                            Name = "Node Operator",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Read-only audit and operations access.",
                            IsSystem = true,
                            Key = "auditor",
                            Name = "Auditor",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneRolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("permission_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("control_plane_role_permission", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 2L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 3L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 4L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 5L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 6L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 7L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 8L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 9L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 10L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 11L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 1L,
                            PermissionId = 12L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 2L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 3L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 4L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 5L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 6L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 2L,
                            PermissionId = 7L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 4L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 6L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 7L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            RoleId = 3L,
                            PermissionId = 8L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.NodeCapabilitySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("capabilities_json");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checksum");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("node_id");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("schema_version");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("NodeId", "Checksum");

                    b.HasIndex("NodeId", "IsCurrent")
                        .HasDatabaseName("node_capability_snapshot_current_idx")
                        .HasFilter("is_current");

                    b.ToTable("node_capability_snapshot", (string)null);
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.NodeHealthSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CheckedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DependencyStatusJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("dependency_status_json");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("node_id");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("NodeId", "CheckedAt");

                    b.HasIndex("Status", "CheckedAt");

                    b.ToTable("node_health_snapshot", null, t =>
                        {
                            t.HasCheckConstraint("ck_node_health_snapshot_status", "status in ('healthy', 'warning', 'down', 'timeout', 'malformed', 'unknown')");
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.StoreDomainRegistry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<string>("NormalizedDomain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_domain");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("store_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedDomain")
                        .IsUnique()
                        .HasDatabaseName("store_domain_registry_active_domain_uq")
                        .HasFilter("disabled_at is null");

                    b.HasIndex("StoreId");

                    b.ToTable("store_domain_registry", null, t =>
                        {
                            t.HasCheckConstraint("ck_store_domain_registry_status", "status in ('pending', 'verified', 'disabled')");
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.StoreRegistry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("NodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("node_id");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StoreKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("store_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("NodeId", "StoreKey")
                        .IsUnique()
                        .HasDatabaseName("store_registry_active_node_store_key_uq")
                        .HasFilter("archived_at is null");

                    b.ToTable("store_registry", null, t =>
                        {
                            t.HasCheckConstraint("ck_store_registry_status", "status in ('active', 'disabled', 'archived')");
                        });
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequirePasswordChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "93f5cdac-43de-4895-8426-2048c228e76d",
                            ConcurrencyStamp = "02d86d56-8e63-4d2e-92f8-81b154ba0532",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "b7af6842-02fa-4af4-8f61-ae04a49644a2",
                            ConcurrencyStamp = "75e8afa8-8df5-4431-a220-ac56b1fd0cda",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.CommerceNodeCredential", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUser", "CreatedByAdminUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.CommerceNode", "Node")
                        .WithMany("Credentials")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUser", "RevokedByAdminUser")
                        .WithMany()
                        .HasForeignKey("RevokedByAdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByAdminUser");

                    b.Navigation("Node");

                    b.Navigation("RevokedByAdminUser");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.CommerceNodeEndpoint", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.CommerceNode", "Node")
                        .WithMany("Endpoints")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlAction", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.CommerceNode", "Node")
                        .WithMany("Actions")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.StoreRegistry", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Node");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlActionAttempt", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlAction", "Action")
                        .WithMany("Attempts")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlAuditLog", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUser", "ActorAdminUser")
                        .WithMany()
                        .HasForeignKey("ActorAdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlAction", "ControlAction")
                        .WithMany()
                        .HasForeignKey("ControlActionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.CommerceNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.StoreRegistry", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorAdminUser");

                    b.Navigation("ControlAction");

                    b.Navigation("Node");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUser", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUser", "StatusChangedByAdminUser")
                        .WithMany()
                        .HasForeignKey("StatusChangedByAdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StatusChangedByAdminUser");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUserPermission", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUser", "AdminUser")
                        .WithMany("DirectPermissions")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUser", "CreatedByAdminUser")
                        .WithMany("CreatedDirectPermissionGrants")
                        .HasForeignKey("CreatedByAdminUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_control_plane_admin_user_permission_control_plane_admin_us~1");

                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlPlanePermission", "Permission")
                        .WithMany("DirectUsers")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("CreatedByAdminUser");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUserRole", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUser", "AdminUser")
                        .WithMany("Roles")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneRolePermission", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlPlanePermission", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.NodeCapabilitySnapshot", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.CommerceNode", "Node")
                        .WithMany("CapabilitySnapshots")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.NodeHealthSnapshot", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.CommerceNode", "Node")
                        .WithMany("HealthSnapshots")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.StoreDomainRegistry", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.StoreRegistry", "Store")
                        .WithMany("Domains")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.StoreRegistry", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.ControlPlane.CommerceNode", "Node")
                        .WithMany("Stores")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorShop.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BlazorShop.Domain.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.CommerceNode", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("CapabilitySnapshots");

                    b.Navigation("Credentials");

                    b.Navigation("Endpoints");

                    b.Navigation("HealthSnapshots");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlAction", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneAdminUser", b =>
                {
                    b.Navigation("CreatedDirectPermissionGrants");

                    b.Navigation("DirectPermissions");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlanePermission", b =>
                {
                    b.Navigation("DirectUsers");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.ControlPlaneRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BlazorShop.Domain.Entities.ControlPlane.StoreRegistry", b =>
                {
                    b.Navigation("Domains");
                });
#pragma warning restore 612, 618
        }
    }
}
