namespace BlazorShop.Storefront.Components.Contracts.Product;

public sealed record ProductPurchasePanelModel(
    Guid ProductId,
    string ProductName,
    string CurrencyCode,
    string BaseUnitPriceValue,
    Guid? ResolvedVariantId,
    string? InitialSku,
    string? InitialGtin,
    string? InitialMainImageUrl,
    int InitialStockValue,
    int MinOrderQuantity,
    int? MaxOrderQuantity,
    int QuantityStep,
    bool FreeShipping,
    string? DeliveryEstimateText,
    bool CanSubmitInitialPurchase,
    string PurchaseMessage,
    string PurchaseBlockMessage,
    IReadOnlyList<string> InitialValidationMessages,
    IReadOnlyList<ProductPurchaseOptionItem> VariationOptions,
    IReadOnlyList<ProductPurchaseVariantItem> Variants,
    string CartUrl)
{
    public static ProductPurchasePanelModel Empty { get; } = new(
        Guid.Empty,
        "Product",
        "USD",
        "0.00",
        null,
        null,
        null,
        null,
        0,
        1,
        null,
        1,
        false,
        null,
        false,
        "This product cannot be added to cart right now.",
        "Currently unavailable.",
        ["Currently unavailable."],
        [],
        [],
        "/my-cart");
}
