<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BlazorShop.Storefront.Components.Primitives</RootNamespace>
    <PackageId>BlazorShop.Storefront.Components.Primitives</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorShop.Storefront.Components\BlazorShop.Storefront.Components.csproj" />
  </ItemGroup>
</Project>
