<#
.SYNOPSIS
Verifies Storefront V2 CSS artifacts are reproducible from their project-local Tailwind pipelines.

.DESCRIPTION
dotnet build is intentionally not treated as CSS generation here: the Storefront V2 projects keep
Tailwind as a Node toolchain step, so stale tracked CSS can survive a .NET-only build.

BlazorShop.Storefront.V2 owns the host/global CSS artifact at wwwroot/css/site.css.
BlazorShop.Storefront.V2.WASM owns interactive cart, checkout, and account CSS at
wwwroot/css/wasm-site.css. The files are separate because hosted WASM static assets merge at the
host root and cannot reuse the same css/site.css logical path.

This gate runs npm ci and the project-local npm run tailwind:build for each project, copies the
generated bytes to obj/storefront-css-proof, restores the original tracked file bytes, and then
compares original versus regenerated content. On success, temp evidence is removed unless
-KeepEvidence is passed. On drift, candidate CSS remains under obj/storefront-css-proof.

To intentionally refresh CSS, run npm run tailwind:build in the owning project, review the tracked
CSS diff, then rerun this script from the repository root.
#>

[CmdletBinding()]
param(
    [switch]$KeepEvidence
)

$ErrorActionPreference = "Stop"

function Resolve-RepositoryRoot {
    $root = Resolve-Path (Join-Path $PSScriptRoot "..\..")
    return $root.Path
}

function Assert-CurrentLocationIsRepositoryRoot {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepositoryRoot
    )

    $current = (Resolve-Path (Get-Location)).Path
    if (-not [string]::Equals($current, $RepositoryRoot, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Run this script from repository root: $RepositoryRoot"
    }
}

function Invoke-CheckedCommand {
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath,

        [Parameter(Mandatory = $true)]
        [string[]]$Arguments,

        [Parameter(Mandatory = $true)]
        [string]$ProjectName
    )

    Write-Host "[$ProjectName] $FilePath $($Arguments -join ' ')"
    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "[$ProjectName] Command failed with exit code ${LASTEXITCODE}: $FilePath $($Arguments -join ' ')"
    }
}

function Test-ByteArrayEquals {
    param(
        [Parameter(Mandatory = $true)]
        [byte[]]$Left,

        [Parameter(Mandatory = $true)]
        [byte[]]$Right
    )

    if ($Left.Length -ne $Right.Length) {
        return $false
    }

    for ($index = 0; $index -lt $Left.Length; $index++) {
        if ($Left[$index] -ne $Right[$index]) {
            return $false
        }
    }

    return $true
}

function Assert-UnderRepository {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepositoryRoot,

        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    $resolved = [System.IO.Path]::GetFullPath($Path)
    $rootWithSeparator = $RepositoryRoot.TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar
    if (-not $resolved.StartsWith($rootWithSeparator, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to touch path outside repository: $resolved"
    }
}

$repositoryRoot = Resolve-RepositoryRoot
Assert-CurrentLocationIsRepositoryRoot -RepositoryRoot $repositoryRoot

$proofRoot = Join-Path $repositoryRoot "obj\storefront-css-proof"
Assert-UnderRepository -RepositoryRoot $repositoryRoot -Path $proofRoot

$projects = @(
    @{
        Name = "BlazorShop.Storefront.V2"
        ProjectRoot = "BlazorShop.PresentationV2\BlazorShop.Storefront.V2"
        TrackedCss = "wwwroot\css\site.css"
        CandidateCss = "obj\storefront-css-proof\v2\site.css"
    },
    @{
        Name = "BlazorShop.Storefront.V2.WASM"
        ProjectRoot = "BlazorShop.PresentationV2\BlazorShop.Storefront.V2.WASM"
        TrackedCss = "wwwroot\css\wasm-site.css"
        CandidateCss = "obj\storefront-css-proof\v2-wasm\wasm-site.css"
    }
)

$hasDrift = $false

foreach ($project in $projects) {
    $projectName = $project.Name
    $projectRoot = Join-Path $repositoryRoot $project.ProjectRoot
    $trackedCssPath = Join-Path $projectRoot $project.TrackedCss
    $candidateCssPath = Join-Path $repositoryRoot $project.CandidateCss

    foreach ($requiredRelativePath in @("package.json", "package-lock.json", "tailwind.config.js", "wwwroot\css\input.css", $project.TrackedCss)) {
        $requiredPath = Join-Path $projectRoot $requiredRelativePath
        if (-not (Test-Path -LiteralPath $requiredPath)) {
            throw "[$projectName] Missing required CSS pipeline file: $requiredPath"
        }
    }

    $candidateDirectory = Split-Path -Parent $candidateCssPath
    New-Item -ItemType Directory -Force -Path $candidateDirectory | Out-Null

    $originalBytes = [System.IO.File]::ReadAllBytes($trackedCssPath)
    $generatedBytes = $null

    try {
        Push-Location $projectRoot
        try {
            Invoke-CheckedCommand -FilePath "npm" -Arguments @("ci") -ProjectName $projectName
            Invoke-CheckedCommand -FilePath "npm" -Arguments @("run", "tailwind:build") -ProjectName $projectName
        }
        finally {
            Pop-Location
        }

        $generatedBytes = [System.IO.File]::ReadAllBytes($trackedCssPath)
        [System.IO.File]::WriteAllBytes($candidateCssPath, $generatedBytes)
    }
    finally {
        [System.IO.File]::WriteAllBytes($trackedCssPath, $originalBytes)
    }

    if (-not (Test-ByteArrayEquals -Left $originalBytes -Right $generatedBytes)) {
        Write-Host "[$projectName] CSS drift detected in $trackedCssPath. Candidate output: $candidateCssPath" -ForegroundColor Red
        $hasDrift = $true
    }
    else {
        Write-Host "[$projectName] CSS is reproducible: $trackedCssPath"
    }
}

if ($hasDrift) {
    exit 1
}

if (-not $KeepEvidence -and (Test-Path -LiteralPath $proofRoot)) {
    $resolvedProofRoot = [System.IO.Path]::GetFullPath($proofRoot)
    $expectedProofRoot = [System.IO.Path]::GetFullPath((Join-Path $repositoryRoot "obj\storefront-css-proof"))
    if (-not [string]::Equals($resolvedProofRoot, $expectedProofRoot, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Refusing to clean unexpected proof path: $resolvedProofRoot"
    }

    Remove-Item -LiteralPath $proofRoot -Recurse -Force
}

Write-Host "Storefront V2 CSS reproducibility gate passed."
