namespace BlazorShop.Tests.PresentationV2.Storefront
{
    using System.Diagnostics;
    using System.Xml.Linq;

    using Xunit;

    public sealed class StorefrontGeneratedClientFoundationTests
    {
        private const string ClientProjectPath = "BlazorShop.PresentationV2/BlazorShop.Storefront.Client/BlazorShop.Storefront.Client.csproj";
        private const string GeneratedClientPath = "BlazorShop.PresentationV2/BlazorShop.Storefront.Client/Generated/StorefrontClient.g.cs";
        private const string GeneratorConfigPath = "BlazorShop.PresentationV2/BlazorShop.Storefront.Client/nswag.storefront.client.json";
        private const string GeneratorScriptPath = "scripts/generate-storefront-client.ps1";

        [Fact]
        public void StorefrontClientProject_HasNoBackendOrStorefrontV2References()
        {
            var references = ReadProjectReferences(ClientProjectPath);
            var forbidden = references
                .Where(IsForbiddenStorefrontClientReference)
                .OrderBy(reference => reference, StringComparer.OrdinalIgnoreCase)
                .ToArray();

            Assert.Empty(forbidden);
        }

        [Fact]
        public void StorefrontClientGeneration_IsPinnedAndDeterministic()
        {
            var config = ReadRepositoryFile(GeneratorConfigPath);
            var script = ReadRepositoryFile(GeneratorScriptPath);
            var generatedClient = ReadRepositoryFile(GeneratedClientPath);

            Assert.Contains("\"nswag.consolecore\"", ReadRepositoryFile(".config/dotnet-tools.json"), StringComparison.Ordinal);
            Assert.Contains("\"version\": \"14.7.1\"", ReadRepositoryFile(".config/dotnet-tools.json"), StringComparison.Ordinal);
            Assert.Contains("storefront-openapi.snapshot.json", config, StringComparison.Ordinal);
            Assert.Contains("\"openApiToCSharpClient\"", config, StringComparison.Ordinal);
            Assert.Contains("\"namespace\": \"BlazorShop.Storefront.Client\"", config, StringComparison.Ordinal);
            Assert.Contains("dotnet nswag run", script, StringComparison.Ordinal);

            Assert.Contains("<auto-generated>", generatedClient, StringComparison.Ordinal);
            Assert.Contains("Generated using the NSwag toolchain v14.7.1.0", generatedClient, StringComparison.Ordinal);
            Assert.Contains("StorefrontConfigurationClient", generatedClient, StringComparison.Ordinal);
            Assert.Contains("StorefrontCatalogClient", generatedClient, StringComparison.Ordinal);
            Assert.Contains("StorefrontCartClient", generatedClient, StringComparison.Ordinal);
            Assert.Contains("StorefrontCheckoutClient", generatedClient, StringComparison.Ordinal);
            Assert.Contains("StorefrontAuthClient", generatedClient, StringComparison.Ordinal);
            Assert.DoesNotContain("HandleProviderCallback", generatedClient, StringComparison.Ordinal);
            Assert.DoesNotContain("HandleWebhook", generatedClient, StringComparison.Ordinal);
        }

        [Fact]
        public void StorefrontClientProject_BuildsGeneratedClient()
        {
            var repositoryRoot = FindRepositoryRoot();
            var result = RunProcess(
                "dotnet",
                ["build", RepositoryPath(ClientProjectPath), "--no-restore"],
                repositoryRoot);

            Assert.True(
                result.ExitCode == 0,
                string.Join(
                    Environment.NewLine,
                    "Generated Storefront C# client project did not build.",
                    $"Exit code: {result.ExitCode}",
                    "stdout:",
                    result.StandardOutput,
                    "stderr:",
                    result.StandardError));
        }

        private static IReadOnlyList<string> ReadProjectReferences(string relativeProjectPath)
        {
            var projectPath = RepositoryPath(relativeProjectPath);
            var projectDirectory = Path.GetDirectoryName(projectPath)
                ?? throw new DirectoryNotFoundException($"Could not resolve project directory for {relativeProjectPath}.");
            var document = XDocument.Load(projectPath);

            return document.Descendants("ProjectReference")
                .Select(element => element.Attribute("Include")?.Value)
                .Where(value => !string.IsNullOrWhiteSpace(value))
                .Select(value => Path.GetFullPath(Path.Combine(projectDirectory, value!)))
                .Select(path => Path.GetRelativePath(FindRepositoryRoot(), path).Replace('\\', '/'))
                .OrderBy(path => path, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        private static bool IsForbiddenStorefrontClientReference(string reference)
        {
            var normalized = reference.Replace('\\', '/');

            return normalized.Contains("/BlazorShop.Domain/", StringComparison.OrdinalIgnoreCase)
                || normalized.Contains("/BlazorShop.Application/", StringComparison.OrdinalIgnoreCase)
                || normalized.Contains("/BlazorShop.Infrastructure/", StringComparison.OrdinalIgnoreCase)
                || normalized.Contains("/BlazorShop.CommerceNode.API/", StringComparison.OrdinalIgnoreCase)
                || normalized.Contains("/BlazorShop.ControlPlane.API/", StringComparison.OrdinalIgnoreCase)
                || normalized.Contains("/BlazorShop.Storefront.V2/", StringComparison.OrdinalIgnoreCase);
        }

        private static string ReadRepositoryFile(string relativePath)
        {
            return File.ReadAllText(RepositoryPath(relativePath));
        }

        private static string RepositoryPath(string relativePath)
        {
            return Path.Combine(FindRepositoryRoot(), relativePath.Replace('/', Path.DirectorySeparatorChar));
        }

        private static string FindRepositoryRoot()
        {
            var directory = new DirectoryInfo(AppContext.BaseDirectory);
            while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "BlazorShop.sln")))
            {
                directory = directory.Parent;
            }

            return directory?.FullName ?? throw new DirectoryNotFoundException("Could not locate repository root.");
        }

        private static ProcessResult RunProcess(string fileName, IReadOnlyList<string> arguments, string workingDirectory)
        {
            var startInfo = new ProcessStartInfo
            {
                FileName = fileName,
                WorkingDirectory = workingDirectory,
                RedirectStandardError = true,
                RedirectStandardOutput = true,
                UseShellExecute = false,
            };

            foreach (var argument in arguments)
            {
                startInfo.ArgumentList.Add(argument);
            }

            using var process = Process.Start(startInfo)
                ?? throw new InvalidOperationException($"Failed to start process '{fileName}'.");
            var standardOutput = process.StandardOutput.ReadToEnd();
            var standardError = process.StandardError.ReadToEnd();
            process.WaitForExit();

            return new ProcessResult(process.ExitCode, standardOutput, standardError);
        }

        private sealed record ProcessResult(int ExitCode, string StandardOutput, string StandardError);
    }
}
