<Project>
  <PropertyGroup>
    <StorefrontClientPackageVersion>1.0.0-local</StorefrontClientPackageVersion>
    <StorefrontRuntimePackageVersion>1.0.0-local</StorefrontRuntimePackageVersion>
    <StorefrontPresentationPackageVersion>1.0.0-local</StorefrontPresentationPackageVersion>
    <StorefrontComponentsPackageVersion>1.0.0-local</StorefrontComponentsPackageVersion>
    <StorefrontBrowserPackageVersion>1.0.0-local</StorefrontBrowserPackageVersion>
  </PropertyGroup>
</Project>
